### ISSUE TITLE
/sys/devices/system/cpu/online isn't closed if output is too big

### ISSUE THREAD

**Issue by nullp0tr** [bolinfest/opensnoop-native#1]
in function `getOnlineCpus` you have: 

```c
int getOnlineCpus(int **cpus, size_t *numCpu) {
  int fd = open("/sys/devices/system/cpu/online", O_RDONLY | O_CLOEXEC);
  if (fd < 0) {
    return -1;
  }

  const int bufSize = 256;
  char buf[bufSize];
  int numRead = read(fd, buf, bufSize);
  if (numRead == bufSize || numRead == 0) {
    // We are not prepared for the output to be this big (or empty)!
    errno = EINVAL;
    return -1;
  }
  if (close(fd) < 0) {
    return -1;
  }
  ....
```
this returns -1 before closing file descriptor. Also if you're okay with using dynamic memory it's possible to loop over the `read` call. I can send a patch for both if interested, though I might use a `goto`;)

**Comment by bolinfest** [comment]
@nullp0tr Thanks for the report! As you can see, I think this was easy enough to fix without a `goto`.

For the `read(2)`, I decided to avoid dynamic memory because it didn't seem worth the code complexity here. If I were to promote this code to be used in production, then I guess I would fix it, but this is mainly for learning.

**Comment by nullp0tr** [comment]
@bolinfest you're welcome:) and fair enough with the `read(2)`. You're article about the project was quite interesting by the way!
